# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0d3e2aa382e2a914c7c84e19896e8da55875d2edf0cc0f1b7bb54bcf1fef0f5c450e5b902256d0ee14e7e5ce4d1ed8ea8fcb24ca31b11f82decdcfc42d953f

test:
  secret_key_base: 0dc1fbac0f612703925778f345825cbdba77011a3301777770c335490aa6d1e82a88d7ed859f789871b0baec01a5a117f45583f6cbb978e23b67e7d87d84ee43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
